name: FreeBSD

on: [workflow_dispatch]

jobs:
  alpha-x64-freebsd:
      runs-on: ubuntu-latest
      env:
        CARGO_TERM_COLOR: always
        LANG: zh_CN.UTF-8
        LANGUAGE: zh_CN:zh
        LC_ALL: zh_CN.UTF-8
      steps:
      - uses: actions/checkout@v4
        with:
          # v2 defaults to a shallow checkout, but we need at least to the previous tag
          fetch-depth: 0

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Add Rust Target
        run: rustup target add x86_64-unknown-freebsd

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          save-if: false
          
      - name: 汉化
        run: |
          sudo apt-get update
          sudo apt-get install language-pack-zh-hans -y
    
      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install clang lld libc6-dev-amd64-cross
          sudo apt-get install -y libxslt1.1 libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: 安装 FreeBSD 头文件和库
        run: |
          wget https://download.freebsd.org/ftp/releases/amd64/amd64/13.4-RELEASE/base.txz
          mkdir freebsd-sysroot
          tar -xf base.txz -C freebsd-sysroot

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      
      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm run prebuild x86_64-unknown-freebsd

      #- name: Tauri build
      #  continue-on-error: true
      #  uses: tauri-apps/tauri-action@v0
      #  env:
      #    NODE_OPTIONS: "--max_old_space_size=4096"
      #  with:
      #    tauriScript: pnpm
      #    args: --target x86_64-unknown-freebsd
      - name: 编译
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          pnpm tauri build --target x86_64-unknown-freebsd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-freebsd
          path: src-tauri/target/x86_64-unknown-freebsd/release/bundle
      